/**
 * The closed "fact world" a category agent is allowed to reference — see
 * docs/18-m1b-ai-agent-architecture.md §5. Every item is a plain-fact
 * string built entirely from M1a's already-computed data (lighthouse /
 * site_signals agent output); nothing here is ever generated by a model.
 */
export type EvidenceItem = {
  id: string;
  fact: string;
};

/**
 * Numbers a list of candidate facts as EV1, EV2, ... Falsy/blank entries
 * are dropped rather than becoming an empty evidence item — callers can
 * freely pass conditional facts (`hasContactForm ? "..." : null`) without
 * checking truthiness themselves.
 */
export function buildEvidenceList(
  facts: Array<string | null | undefined | false>,
): EvidenceItem[] {
  return facts
    .filter((fact): fact is string => typeof fact === "string" && fact.trim().length > 0)
    .map((fact, index) => ({ id: `EV${index + 1}`, fact: fact.trim() }));
}

/** Serializes the evidence list into the plain-text block the prompt embeds. */
export function formatEvidenceForPrompt(evidence: EvidenceItem[]): string {
  if (evidence.length === 0) {
    return "(No evidence was available for this category on this scan.)";
  }
  return evidence.map((item) => `${item.id}: ${item.fact}`).join("\n");
}
